--- #YAML:1.0
name:               MySQL-QueryMulti
version:            0.02
abstract:           module for querying multiple MySQL databases in parallel
author:
    - John Gravatt <gravattj@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::mysql:        4.019
    DBI:               1.6
    Math::BigInt:      1.994
    Math::Complex:     1.56
    Moose:             2.0403
    SQL::Statement:    1.33
    Term::ReadLine:    1.07
    Test::More:        0
    Text::ASCIITable:  0.18
    Time::HiRes:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
